also called verbs:
select(), which returns a subset of the columns,
filter(), that is able to return a subset of the rows,
arrange(), that reorders the rows according to single or multiple variables,
mutate(), used to add columns from existing data,
summarise(), which reduces each group to a single row by calculating aggregate measures.

select == variables
=====
select(df, Group, Sum)
returns everythings but this set of columns
select(hflights, -(DepTime:AirTime))
starts_with("X"): every name that starts with "X",
ends_with("X"): every name that ends with "X",
contains("X"): every name that contains "X",
matches("X"): every name that matches "X", which can be a regular expression,
num_range("x", 1:5): the variables named x01, x02, x03, x04 and x05,
one_of(x): every name that appears in x, which should be a character vector.

mutate == observations
====================
mutate(df, loss =   arrDelay- depDelay)

m1 <- mutate(hflights, loss = ArrDelay - DepDelay, loss_percent = (ArrDelay - DepDelay) / DepDelay * 100)

# Remove the redundancy from your previous exercise and reuse loss to define the loss_percent variable.
# Assign the result to m2
m2 <- mutate(hflights, loss = ArrDelay - DepDelay, loss_percent = loss / DepDelay * 100)

# Add the three variables as described in the third exercise and save the result to m3
m3 <- mutate(hflights, TotalTaxi = TaxiIn + TaxiOut, 
                       ActualGroundTime = ActualElapsedTime - AirTime, 
                       Diff = TotalTaxi - ActualGroundTime)
                       
filter == variables
=========
                       
filter(hflights, Cancelled == 1)


x < y, TRUE if x is less than y
x <= y, TRUE if x is less than or equal to y
x == y, TRUE if x equals y
x != y, TRUE if x does not equal y
x >= y, TRUE if x is greater than or equal to y
x > y, TRUE if x is greater than y
x %in% c(a, b, c), TRUE if x is in the vector c(a, b, c)

# All flights that traveled 3000 miles or more.
f1 <- filter(hflights, Distance >= 3000)

# All flights flown by one of JetBlue, Southwest, or Delta airlines
f2 <- filter(hflights, UniqueCarrier %in% c("JetBlue", "Southwest", "Delta"))

# All flights where taxiing took longer than flying
f3 <- filter(hflights, TaxiIn + TaxiOut > AirTime)

# all flights that departed before 5am or arrived after 10pm.
f1 <- filter(hflights, DepTime < 500 | ArrTime > 2200)

# all flights that departed late but arrived ahead of schedule
f2 <- filter(hflights, DepDelay > 0, ArrDelay < 0)

# all cancelled weekend flights
f3 <- filter(hflights, Cancelled == 1, DayOfWeek %in% c(6,7))

# all flights that were cancelled after being delayed
f4 <- filter(hflights, Cancelled == 1, !is.na(DepDelay))



arrange == observations
============
arrange(hflights, Distance, ArrDelay)#ArrDElay is the ties-breaker when pordering by Distance
# Arrange dtc by departure delays
a1 <- arrange(dtc, DepDelay)

# Arrange dtc so that cancellation reasons are grouped
a2 <- arrange(dtc, CancellationCode)

# Arrange according to carrier and departure delays
a3 <- arrange(hflights, UniqueCarrier, DepDelay)


# Arrange according to carrier and decreasing departure delays
a1 <- arrange(hflights, UniqueCarrier, desc(DepDelay))

# Arrange flights by total delay (normal order).
a2 <- arrange(hflights, desc(DepDelay + ArrDelay))

# Filter out flights leaving to DFW before 8am and arrange according to decreasing AirTime 
a3 <- arrange(filter(hflights, Dest == "DFW", DepTime < 800), desc(AirTime))


summarise == groups
=========

# Determine the shortest and longest distance flown and save statistics to min_dist and max_dist resp.
s1 <- summarise(hflights, min_dist = min(Distance), max_dist = max(Distance))

# Determine the longest distance for diverted flights, save statistic to max_div. Use a one-liner!
s2 <- summarise(filter(hflights, Diverted == 1), max_div = max(Distance))
# Calculate summarizing statistics for flights that have an ArrDelay that is not NA
temp1 <- filter(hflights, !is.na(ArrDelay))
s1 <- summarise(temp1, earliest= min(ArrDelay), average = mean(ArrDelay), latest = max(ArrDelay), sd = sd(ArrDelay))

# Calculate the maximum taxiing difference for flights that have taxi data available
temp2 <- filter(hflights, !is.na(TaxiIn), !is.na(TaxiOut))
s2 <- summarise(temp2, max_taxi_diff=max(abs(TaxiIn - TaxiOut)))


# Calculate the summarizing statistics of hflights
s1 <- summarise(hflights, n_obs=n(), n_carrier = n_distinct(UniqueCarrier), n_dest = n_distinct(Dest), dest100 = nth(Dest, 100))

# Calculate the summarizing statistics for flights flown by American Airlines (carrier code "American")
aa <- filter(hflights, UniqueCarrier == "American")
s2 <- summarise(aa, n_flights=n(), n_canc = sum(Cancelled == 1), p_canc = mean(Cancelled == 1)*100, avg_delay = mean(ArrDelay, na.rm=TRUE))



Chaining your functions:
======================


# Write the 'piped' version of the English sentences.
p <- hflights %>%
    mutate(diff = TaxiOut - TaxiIn) %>%
    filter(!is.na(diff)) %>%
    summarise(avg = mean(diff))


# Part 1, concerning the selection and creation of columns
d <- hflights %>% 
    select(Dest, UniqueCarrier, Distance, ActualElapsedTime) %>%
    mutate(RealTime = ActualElapsedTime + 100, mph = Distance/RealTime*60) 

# Part 2, concerning flights that had an actual average speed of less then 70 mph.
d %>% filter(!is.na(mph), mph <= 70) %>%
        summarise(n_less = n(), n_dest = n_distinct(Dest), min_dist = min(Distance), max_dist = max(Distance))

# Solve the exercise using a combination of dplyr verbs and %>%
hflights %>%
    select(Dest, Cancelled, Distance, ActualElapsedTime, Diverted) %>%
    mutate(RealTime = ActualElapsedTime + 100, mph = Distance / RealTime * 60) %>%
    filter(mph <= 105 | Cancelled == 1 | Diverted == 1) %>%
    summarise(n_non = n(),
              p_non = n_non / nrow(hflights) * 100,
              n_dest = n_distinct(Dest),
              min_dist = min(Distance),
              max_dist = max(Distance))
              
              
# Count the number of overnight flights
hflights %>% 
    filter(!is.na(ArrTime), !is.na(DepTime), ArrTime < DepTime) %>%
    summarise(n = n())